volumes:
  security_users_data:
  messaging_db_data:
  files_db_data:
  user-details-data:
  notifications-data:
  redis_data:
  es_data:
    driver: local

networks:
  users-network:
    driver: bridge

  elastic:
    driver: bridge

services:
  users-auth-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: security_users_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - security_users_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  messaging-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: messaging_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - messaging_db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  notifications-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - notifications-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"

  files-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - files_db_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  metadata-elasticsearch-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      # Ограничиваем память Java, чтобы Docker не съел все ресурсы ПК
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # --- НАСТРОЙКИ БЕЗОПАСНОСТИ ---
      - xpack.security.enabled=true
      # Отключаем SSL (HTTPS) для HTTP API, чтобы в Java не возиться с сертификатами
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"