version: '3.8'
name: alexgls-messenger-prod
volumes:
  security_users_data:
  messaging_db_data:
  files_db_data:
  notifications-data:
  redis-data:
  es_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  # --- DATABASES ---
  users-auth-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: security_users_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - security_users_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  messaging-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: messaging_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - messaging_db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - app-network

  notifications-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - notifications-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - app-network

  files-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - files_db_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - app-network

  metadata-elasticsearch-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: metadata-elasticsearch-db
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # --- INFRASTRUCTURE ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
      ZOOKEEPER_LOG_DIR: /var/lib/zookeeper/log
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network

  connections-redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "AS04SERa1", "--notify-keyspace-events", "Ex" ]
    volumes:
      - redis-data:/data
    networks:
      - app-network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
       - app-network

  # --- MICROSERVICES ---
  api-gateway-service:
    build: ./ApiGatewayService
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AUTH_SERVICE_URL=http://auth-service:8085
      - MESSAGING_SERVICE_URL=http://messages-service:8087
      - FILES_SERVICE_URL=http://db-content-storage-service:8089
      - REGISTRATION_SERVICE_URL=http://registration-service:8082
      - CONNECTIONS_SERVICE_URL=http://connections-service:8086
      - SEARCH_SERVICE_URL=http://search-data-service:8093
      - ANALYSIS_SERVICE_URL=http://content-analysis-service:8094
      - METADATA_SERVICE_URL=http://metadata-service:8095
      - NOTIFICATIONS_SERVICE_URL=http://notifications-service:8091
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - auth-service
      - messages-service
    networks:
      - app-network

  auth-service:
    build: ./AuthService
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-auth-db:5432/security_users_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_SERVICE_URL=http://auth-service:8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - users-auth-db
      - kafka
    networks:
      - app-network

  connections-service:
    build: ./ConnectionsService
    container_name: connections-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8085
      - MESSAGES_STORAGE_SERVICE=http://messages-service:8087
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECTIONS_REDIS_DB_URL=connections-redis
      - CONNECTIONS_REDIS_DB_PASSWORD=${CONNECTIONS_REDIS_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - kafka
      - connections-redis
    networks:
      - app-network

  messages-service:
    build: ./MessageStorageService
    container_name: messages-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://messaging-db:5432/messaging_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_SERVICE_URL=http://auth-service:8085
      - CONNECTIONS_SERVICE=http://connections-service:8086
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - AES_KEY=${AES_KEY}
      - HMAC_KEY=${HMAC_KEY}
    depends_on:
      - messaging-db
      - kafka
    networks:
      - app-network

  db-content-storage-service:
    build: ./ContentStorageService
    container_name: db-content-storage-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://files-db:5432/files_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_SERVICE_URL=http://auth-service:8085
      - MESSAGE_STORAGE_SERVICE=http://messages-service:8087
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - files-db
    networks:
      - app-network

  notifications-service:
    build: ./NotificationsService
    container_name: notifications-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notifications-db:5432/notifications_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_SERVICE_URL=http://auth-service:8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - notifications-db
      - kafka
    networks:
      - app-network

  search-data-service:
    build: ./SearchDataService
    container_name: search-data-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8085
      - MESSAGES_SERVICE_URL=http://messages-service:8087
    networks:
      - app-network

  content-analysis-service:
    build: ./ContentAnalysisService
    container_name: content-analysis-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SBER_AUTH_TOKEN=${SBER_AUTH}
    depends_on:
      - kafka
    networks:
      - app-network

  metadata-service:
    build: ./MetadataStorageService
    container_name: metadata-service
    environment:
      - SPRING_ELASTICSEARCH_URIS=metadata-elasticsearch-db:9200
      - SPRING_ELASTICSEARCH_USERNAME=elastic
      - SPRING_ELASTICSEARCH_PASSWORD=elastic
      - AUTH_SERVICE_URL=http://auth-service:8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - metadata-elasticsearch-db
      - kafka
    networks:
      - app-network

  frontend:
    build:
      context: messenger-ui
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api-gateway-service
    volumes:
      - ./messenger-ui/cert:/etc/nginx/ssl:ro
    networks:
      - app-network