global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'spring-boot-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8085'
          - 'messages-service:8087'
          - 'api-gateway-service:8080'
          - 'notifications-service:8091'
          - 'db-content-storage-service:8089'
          - 'connections-service:8086'