server:
  port: 8095

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      enable-auto-commit: false
      max-poll-records: 50

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8085}/.well-known/jwks.json

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:elastic}