server:
  port: 8095

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      enable-auto-commit: false
      max-poll-records: 50

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL}/.well-known/jwks.json

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    username: ${SPRING_ELASTICSEARCH_USERNAME}
    password: ${SPRING_ELASTICSEARCH_PASSWORD}