server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL}/.well-known/jwks.json

frontend:
  cors-address-list: http://localhost:5173


services:
  auth-service: ${AUTH_SERVICE_URL}

