server:
  port: 8086


spring:
  kafka:
    bootstrap-servers: localhost:29092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json

frontend:
  cors-address-list: "https://localhost:8090, https://192.168.0.103:8090, http://localhost:5173, http://192.168.0.103:5173, http://192.168.0.101:"


services:
  auth-service: http://localhost:8085

