server:
  port: 8080
  forward-headers-strategy: native

frontend:
  cors-address-list: ${CORS_ALLOWED_ORIGINS:http://localhost:5173, http://192.168.0.103:5173, http://192.168.0.101}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8085/.well-known/jwks.json}

  # --- НАСТРОЙКА МАРШРУТОВ ---
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- 1. Маршруты для AuthService (:8085) ---
            # Правило для публичных эндпоинтов (логин, ключи)
            - id: auth-public-route
              uri: ${AUTH_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/auth/**, /.well-known/jwks.json, /health

            - id: users-service-route
              uri: ${AUTH_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/users/**, /api/profiles/**

            # --- 2. Маршрут для сервиса сообщений (:8087) ---
            - id: messaging-service-route
              uri: ${MESSAGING_SERVICE_URL:http://localhost:8087}
              predicates:
                # Все эти пути будут перенаправлены на сервис сообщений
                - Path=/api/attachments/**, /api/chats/**, /api/messages/**, /api/pinned-chats/**

            # --- 3. Маршрут для сервиса хранения файлов (:8088) ---

            # --- 4. Маршрут для сервиса файлов в БД (:8089) ---
            - id: files-db-service-route
              uri: ${FILES_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=/api/files/**, /api/media-storage/**

            # --- 5. Маршрут для сервиса входа и регистрации в БД (:8082) ---
            - id: registration-service-route
              uri: ${REGISTRATION_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/verification/**, /api/authentication/**

            # --- 6. Маршрут для WebSocket сервиса (:8086) ---
            - id: connections-route
              uri: ${CONNECTIONS_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/ws-chat/**

            # --- 7. Маршрут для поискового сервиса (:8093) ---
            - id: search-service-route
              uri: ${SEARCH_SERVICE_URL:http://localhost:8093}
              predicates:
                - Path=/api/search/**

            # --- 8. Маршрут для сервиса анализа (:8094) ---
            - id: analysis-service-route
              uri: ${ANALYSIS_SERVICE_URL:http://localhost:8094}
              predicates:
                - Path=/api/analysis/**

            # --- 9. Маршрут для сервиса хранения метаданных (:8095) ---
            - id: metadata-storage-route
              uri: ${METADATA_SERVICE_URL:http://localhost:8095}
              predicates:
                - Path=/api/metadata/**

            # --- 10. Маршрут для сервиса уведомлений (:8091) ---
            - id: notifications-service
              uri: ${NOTIFICATIONS_SERVICE_URL:http://localhost:8091}
              predicates:
                - Path=/api/notifications/**