yandex:
  baseUrl: https://cloud-api.yandex.net/v1/disk/resources
  application-path: /chat_application
  oauth-token:  ${YANDEX_OAUTH}

server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL}/.well-known/jwks.json

services:
  in-database-image-service: ${DB_CONTENT_STORAGE_SERVICE_URL}
  analysis-service: ${ANALYSIS_SERVICE_URL}

webclient:
  timeout: 10


